[package]
name = "unifi-block"
version = "0.1.0"
authors = ["Curt Brune <curt@brune.net>"]
edition = "2018"
description = "Unifi Client Management Tool"

[dependencies]
clap       = "2"
env_logger = "0.7"
log        = "0.4"
unifi      = { path = "../lib" }
